### ISSUE TITLE
Readme/Quick Start: Inaccurate 'Compile & Run'

### ISSUE THREAD

**Issue by e-dant** [e-dant/watcher#13]
On Apple platforms, the user needs to link against two system libraries.

On most (all?) platforms, `c++` should point to the platform's default C++ compiler.

We should change `g++` to `c++` and put something like `$(uname | grep darwin && echo '-framework CoreFoundation -framework CoreServices')` in the compile command from "Quick Start".

**Comment by bosborne** [comment]
I think it would be:

`$(uname | grep Darwin && echo '-framework CoreFoundation -framework CoreServices')`

**Comment by e-dant** [comment]
This is fixed on `next`:

```sh
EXTRAS=$(test "$(uname)" = Darwin && echo '-framework CoreFoundation -framework CoreServices')

c++ -std=c++2a -O3 src/tiny-main.cpp -o watcher $EXTRAS

./watcher
```
