### ISSUE TITLE
Stopping the watcher

### ISSUE THREAD

**Issue by ypujante** [e-dant/watcher#14]
Thank you for the library. I have a one comment:

* I would remove the usage of `static` as you cannot create multiple watchers (the fact that it is an inline function does not change the nature of the `static` variable)

https://github.com/e-dant/watcher/blob/release/sinclude/watcher/watcher.hpp#L838

```cpp
  static auto callback_hook = callback; // here
  const auto callback_adapter =
      [](ConstFSEventStreamRef, /* stream_ref
                                   (required) */
         auto*,                 /* callback_info (required) */
```

You can simply pass the hook in the lambda:

```cpp
  const auto callback_adapter =
      [&callback_hook = callback](ConstFSEventStreamRef, /* stream_ref
                                   (required) */
         auto*,                 /* callback_info (required) */
```

* Secondly, I do not see an "API" to stop the watcher. In my code I need to be able to stop the watcher on command. It looks like the main README talks about it but I don't see a way.

**Comment by e-dant** [comment]
Right on both points! Thanks for spotting the first issue.

The second issue is already on my todo list.

Do you think these fancy GitHub discussions would be a good place to put that list?

**Comment by e-dant** [comment]
I think I can get this done during or before the weekend. There's no reason this should be hard.

**Comment by ypujante** [comment]
I have never used the discussion section, so I don't really have any opinion. There is also a wiki section which might be more appropriate for a to-do list, maybe?

**Comment by e-dant** [comment]
Check out the `next` branch. Let me know if it works for you.

**Comment by ypujante** [comment]
Thank you for taking my comments into consideration. After looking more into it, I don't think I can use your library for my project as I need to be able to have multiple watchers. The way you have implemented `die` as a `static` function that sets a `static` variable guarantees that there can only be one watcher at a time. There is nothing wrong with this approach, but it just won't work for my particular use case.

**Comment by e-dant** [comment]
I'll close this as completed when the next branch is merged. I may make a new issue in the future to support several watchers.
