### ISSUE TITLE
Is `/permissive-`  needed on MSVC in 0.9.0?

### ISSUE THREAD

**Issue by toge** [e-dant/watcher#36]
In 0.9.0, watcher uses "alternative operator representations".

For example, following code uses `and` operator.
https://github.com/e-dant/watcher/blob/release/0.9.0/include/wtr/watcher.hpp#L111-L112

MSVC doesn't understand "alternatvie operator representations" in default.
With `/permissive-` compiler flag, MSVC can understand it.

I think there are two way to solve it.

1. add `/permissive-` compiler flag to CMakeLists.txt.
2. stop using "alternative operator expressions".

I think both are effective.
Can you please decide on a solution?

**Comment by e-dant** [comment]
Should be fixed in https://github.com/e-dant/watcher/commit/9cc5d5cac5884452ca4ef6cab376b2d296307846

**Comment by toge** [comment]
@e-dant 
Sorry.
I miss this modifications.

Close it.
