### ISSUE TITLE
watcher.hpp includes C++20 standard library <bit>

### ISSUE THREAD

**Issue by dovydas-girdvainis** [e-dant/watcher#37]
Hi @e-dant, thanks for your work on issue #32, however, pure C++17 support is still not available.

[wtr/watcher.hpp](https://github.com/e-dant/watcher/blob/release/0.9.2/include/wtr/watcher.hpp#L5) includes the [bit](https://en.cppreference.com/w/cpp/header/bit) library header, which was introduced in C++20 and is preventing compilation on older systems (for example Debian buster).

Is this header needed?

**Comment by e-dant** [comment]
No, it's not. I must have introduced that by mistake. I was fiddling with bit_cast, which is included in the bit header, but memcpy is roughly equivalent. If bit_cast is used anywhere, it's by mistake. I'll fix that.

**Comment by e-dant** [comment]
Our CI needs some work. We should figure out how to use GH actions with containers for better control over the environment. Or even just request an older version of the provided Ubuntu runners.

**Comment by dovydas-girdvainis** [comment]
No problems @e-dant, thanks for the response and clarification.
