### ISSUE TITLE
Compiler error: `chrono:2320:48: note: undefined function '_S_fractional_width' cannot be used in a constant expression`

### ISSUE THREAD

**Issue by e-dant** [e-dant/watcher#41]
Recently, on both the `release` and `next` branches, our CodeQL builds have been coming up with this error:

https://github.com/e-dant/watcher/actions/runs/6684346814/job/18161503474#step:5:74

We also found this error on a Clang build for Linux in development:

https://github.com/e-dant/watcher/actions/runs/6684014904/job/18160816032#step:4:58

This looks and feels like a kind of issue unrelated to our codebase. I am not sure why the issue has only just started to crop up.

Using Nix is always an option to make our builds reproducible and mostly deterministic. Nix was mentioned in a previous build issue: https://github.com/e-dant/watcher/issues/33

**Comment by e-dant** [comment]
Switching to g++ seems to work for the time being: https://github.com/e-dant/watcher/actions/runs/6684463968/job/18161755411

Ideally, we would build on both clang and gcc, and we would do it with Nix.

**Comment by topazus** [comment]
@e-dant I encountered the similar issue here. Maybe you could try to use clang 15 instead of clang 14. see: https://github.com/snitch-org/snitch/pull/138#issuecomment-1781507770

**Comment by e-dant** [comment]
> @e-dant I encountered the similar issue here. Maybe you could try to use clang 15 instead of clang 14. see: [snitch-org/snitch#138 (comment)](https://github.com/snitch-org/snitch/pull/138#issuecomment-1781507770)

Thank you very much -- Lots of good stuff in that linked thread (and I few things I didn't know about how libraries are resolved!)
