### ISSUE TITLE
Windows - rename event is split into two events

### ISSUE THREAD

**Issue by iwubcode** [e-dant/watcher#44]
I'm on Windows 11 and it seems like rename events are sending two events, unlike the example in the README where there is one event with both the old and the new name.  First the old name is sent, then the new name and  `associated` is always `nullptr`.

**Comment by iwubcode** [comment]
I have a potential fix for this, I will post a PR tomorrow...

**Comment by e-dant** [comment]
I have not given Windows the care it deserves. 

Any help getting Windows up to par is greatly appreciated.

**Comment by e-dant** [comment]
Also, if it's easier for you/depending on what you prefer, you can choose to make changes directly in the amalgamated include/wtr/watcher.hpp file. 

Currently, we're set up to amalgamate relevant files in devel/ into include/wtr/watcher.hpp. 

However, it's an extra step, and the library is small enough that working directly on a single file might be more convenient/natural. 

So, up to you, but we can just remove the whole amalgamation step and whatnot if it suits you.

**Comment by iwubcode** [comment]
@e-dant - did you mean to close the other issue?  The PR for this is still open FWIW
