### ISSUE TITLE
Performance Tests

### ISSUE THREAD

**Issue by e-dant** [e-dant/watcher#5]
We need performance benchmarks against the other filesystem watchers. I'm thinking:

- chokidar
- fswatch
- watchman
- notify-rs

We have performance tests, but they're not comparative.

**Comment by e-dant** [comment]
Depending on whether or not some of the other libraries are multithreaded, this might require pinning cpu cores for reliable metrics. I'm not sure how to do that on Windows, but on systems that use posix threads there's an affinity option that might work for this. It's not clear how that will work for Chokidar, though. I think taskset (program) and Grub ('s config file) could be used for that on Linux distros.

**Comment by e-dant** [comment]
These tests could measure the latency between:
1. a filesystem event, and
2. the event being reported by these watchers

The first could be a simple bash script. 

The second could be storing the event, and its timestamp, then writing it out to a file. 

The events could be some set number of different kinds of events and path types: Create, modify, move, remove; Files and directories. 

The events could be created some set number of times and some set interval. Similar things are done in this library's unit tests.

**Comment by fabiospampinato** [comment]
It may be worth measuring also how long it takes to watch a big folder, and how much memory that takes.

**Comment by e-dant** [comment]
> It may be worth measuring also how long it takes to watch a big folder, and how much memory that takes.

Definitely.

I'm curious about different scenarios and profiling metrics.

Some parameters to tweak:
- Directory size
- Nesting level
- File count
- Event interval
- Event kind
- Resource contention

Some parameters to measure:
- Memory usage
- Normalized (over what time?) memory usage
- CPU usage (again, time?)
- CPU usage/thread
- L1, 2 cache misses/hits

We'll get there :)

**Comment by e-dant** [comment]
I'm comfortable with our performance tests and valgrind
