### ISSUE TITLE
Hard times trying PHP FFI to bridge Watcher

### ISSUE THREAD

**Issue by gabrielberthier** [e-dant/watcher#64]
PHP is one of the languages that provide FFI, although with its own quirks. Based on PHP's documentation, it should be relatively easy to implement the bridge between e-dant/watcher and PHP code (Callbacks - FFI)[https://www.php.net/manual/pt_BR/ffi.examples-callback.php]. However I have found it utterly difficult to doing so.

I am experimenting with ReactPHP which uses async functionalities and keeps the code in memory on a long-running process, so my focus is just notify a PHP application that it should be restarted. Likely, doing that using the OS compatible latest lib release would be far easiear than compiling from source, which I have tried and workd (on my machine). Despite it much likely be a buggy behavior related to PHP itself, I wonder if is there any chance that I am using something in the wrong manner, since Python FFI works properly with a similar approach. 

```php
<?php

require_once "vendor/autoload.php";

$headerString = file_get_contents(__DIR__ . "/watcher/watcher-c.h");

$lib = __DIR__ . "/watcher/libwatcher-c.so";

$ffi = FFI::cdef($headerString, $lib);


$executpr = function (\FFI\CData $a, \FFI\CData $b): void {
    echo "Beat";
};


$ffi->wtr_watcher_open(__DIR__ . "/src", $executpr, null);
```

Output: 
PHP Fatal error:  Cannot call callback in Unknown on line 0

I have tried many other ways, most of them warn about a segmentation fault in core or `PHP Fatal error:  Maximum call stack size of 8339456 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion`.

**Comment by e-dant** [comment]
That's a fun one. 

Good news is that it seems (for you, and hopefully me too) reproducible (however painfully in the meantime).

I'll take a look, hopefully this weekend. 

In the interim, depending on how soon you need it, my first steps would be to just boot up gdb, running this php example under it. 

If any frames from watcher are in the stack trace, then at least we know we're being loaded. If we reach the callback (defined in this php file), or just before it, then my suspicions would be around that. But I'd certainly start by narrowing down where things get rough. 

We'll get it sorted:)

**Comment by e-dant** [comment]
Edit: Fixed

**Comment by e-dant** [comment]
This works:

```php

<?php
$d = __DIR__ . "/out/x86_64-unknown-linux-gnu";
$hdr = file_get_contents($d . "/watcher-c.h");
$lib = $d . "/libwatcher-c.so";
$ffi = FFI::cdef($hdr, $lib);
$onevent = function($event, $context) { echo "...\n"; };
$ffi->wtr_watcher_open(__DIR__, $onevent, null);
while (true) {}
?>
```

Note the `while true`.

And the unexpected token string stuff was from an extern "C" scope in the C header, which PHP really ought to be able to deal with... but anyway, maybe we should consider removing the extern scope. 

Be sure to call wtr_watcher_close before exiting PHP, else bad things will happen. I suspect that's what the confusing messages were earlier. 

Anyway, I suspect this will work in the context of a larger application with its own lifecycle.

**Comment by gabrielberthier** [comment]
Thanks a lot for your quick response, Will. Unfortunately I could not make it work using FFI (perhaps it is a problem with my PHP version). Nonetheless, I improved the script to handle closing as follows:
```php
<?php

declare(ticks=1);

$stop = false;

$d = __DIR__ . "/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu";
$hdr = file_get_contents("{$d}/watcher-c.h");
$lib = $d = __DIR__ . "/watcher/out/this/Release/libwatcher-c.so";
$ffi = FFI::cdef($hdr, $lib);
$onevent = function ($event, $context) {
    echo "...\n";
};
$watcher = $ffi->wtr_watcher_open(__DIR__, $onevent, null);

$handleWatcherClose = fn() => $ffi->wtr_watcher_close($watcher);
$handleClose = function () use (&$stop, $handleWatcherClose): never {
    $handleWatcherClose();
    echo "Finished :D" . PHP_EOL;
    $stop = true;
    exit;
};

pcntl_signal(SIGINT, $handleClose);
pcntl_signal(SIGTERM, $handleClose);
register_shutdown_function($handleClose);

while (!$stop) {
    sleep(1);
    echo "HeartBeat" . PHP_EOL;
}

```

The message I still encount whenenever I try to run the script is
```bash
#0 [internal function]: {closure}()
#1 personal/php/PHPWatcher/ffi.php(29): sleep()
#2 {main}
  thrown in php/PHPWatcher/ffi.php on line 11
PHP Fatal error:  Throwing from FFI callbacks is not allowed in php/PHPWatcher/ffi.php on line 29
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Abortado (imagem do núcleo gravada)
```

But I think it is related to this 
> Be sure to call wtr_watcher_close before exiting PHP, else bad things will happen. I suspect that's what the confusing messages were earlier.

**Comment by gabrielberthier** [comment]
I will try a little more to get it sorted here, but appreciate your help earlier.

**Comment by oprypkhantc** [comment]
Just as a side note @gabrielberthier, you should take a look at FrankenPHP :) It supports e-dant/watcher out of the box, as well as ZTS version of PHP which should allow you to use ReactPHP (just not their built-in HTTP server).

**Comment by gabrielberthier** [comment]
That is one of the ways I am currently considering. Thanks!
